name: xanhnow_flutter
description: XanhNow Flutter customer mobile app.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  http: ^1.5.0
  flutter_secure_storage: ^10.0.0-beta.4
  uuid: ^4.5.1
  passkeys: ^2.22.0
  image_picker: 1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
